### ISSUE TITLE
Attach File/Image doesn't scroll with long text

### ISSUE THREAD

**Issue by luxuryluke** [fabianmichael/kirby-markdown-field#106]
I recently updated my plugin and along with Kirby 3.5 I'm having some trouble using the new "attachment" or "file" button on pages with long text.

I switched my blueprint to `text` and the problem goes away. Attaching a file works just fine.

Result: the mini dropdown text that holds the "Select a File" and "Upload a File" are still way up at the top of the page, hidden from view. Upon scrolling up to see it, it's again hidden when losing focus.

I'll switch back to the default text in my blueprints again to regain this functionality, but I'll miss the nice preview formatting of markdown.

**Comment by fabianmichael** [comment]
Resolved in version 2.0.

Closing this, as it seemingly affects version 1.0. Version 2 will be released soon, so I won’t go into that any further. Thanks for your understanding.
