### ISSUE TITLE
file button doesn't work with 'uploads: false'

### ISSUE THREAD

**Issue by daizumi** [fabianmichael/kirby-markdown-field#107]
If I set the option `uploads: false` to the Markdown field, file button stops working (doesn't open any dialogue box when clicking). The documentation says "You have access to the very same options," any idea why this isn't the case for the uploads option?

    textbody:
        label: Body
        type: markdown
        buttons:
          - file
        files: page.images
        uploads: false

**Comment by sylvainjule** [comment]
Well... seems like I haven't plugged it correctly. 👀 I'll have a look!

**Comment by fabianmichael** [comment]
Closing this, as it seemingly affects version 1.0. Version 2 will be released soon, so I won’t go into that any further. Thanks for your understanding.
