### ISSUE TITLE
Toolbar is not 100% width and is not fixed on scrolling

### ISSUE THREAD

**Issue by janstieler** [fabianmichael/kirby-markdown-field#108]
Hi,

in Kirby 3.5.1 the toolbar is not filling the whole width:
![Bildschirmfoto 2021-01-27 um 02 58 53](https://user-images.githubusercontent.com/754880/105931717-fbe78580-604b-11eb-98ef-10ae6e556beb.png)
and on scrolling I have no fixed toolbar. But I know it worked before.

Best

**Comment by fabianmichael** [comment]
Closing this, as it seemingly affects version 1.0. Version 2 will be released soon, so I won’t go into that any further. Thanks for your understanding.
