### ISSUE TITLE
[next] Add plugin version to composer.json

### ISSUE THREAD

**Issue by texnixe** [fabianmichael/kirby-markdown-field#111]
Not specific to this plugin: Kirby reads a plugin's version from the `composer.json` file, so it would be useful to have this information in all plugins to be able to easily check if a plugin is up-to-date.

**Comment by fabianmichael** [comment]
@texnixe Thanks for the hint. I’ll do that from version 2.0 on.

**Comment by fabianmichael** [comment]
With 2.0.0-rc1, I added the version to composer.json.
