### ISSUE TITLE
[next] File uploads to other page

### ISSUE THREAD

**Issue by medienbaecker** [fabianmichael/kirby-markdown-field#117]
While you can set the files location to e.g. the site files like this:

```yml
files: site.files
```
…uploading files will still upload them to the current page.

**Comment by medienbaecker** [comment]
Additionally: when setting `uploads: false` the files button does not work anymore. Both of these features are not documented so I guess they come from the core textarea field and need to be adjusted.

**Comment by fabianmichael** [comment]
@medienbaecker All of these have been addressed with the latest commit. Please note, that the `files` option only determines which files are available in the filepicker. For specifying a different page for uploading, you have to use the `uploads` option and set a `parent` page.

**Comment by fabianmichael** [comment]
@medienbaecker Thank you very much. I just applied for the GitHub sponsors program. Will update the README, once I’m approved.

**Comment by fabianmichael** [comment]
@medienbaecker I now got a [GitHub sponsors profile](https://github.com/sponsors/fabianmichael). Will update the README soon.
