### ISSUE TITLE
File > select not working in builder field

### ISSUE THREAD

**Issue by owzim** [fabianmichael/kirby-markdown-field#132]
Thanks for providing such a versatile field.

It is not working within the [Builder Field](https://github.com/TimOetting/kirby-builder) though

See this gif:

![markdown-field-files](https://user-images.githubusercontent.com/1720088/152347364-e5325198-738e-4bd5-a5ad-bbecdb64d7d9.gif)

No issues as a regular field in page pages.

**Comment by fabianmichael** [comment]
@owzim Hi and thank you for sponsorship. But unfortunately, I cannot help you with this, as the minimum requirement for the Markdown field 2.0 is Kirby 3.6 or later, which is in turn not supported by the builder field.

But the good news is, that the builder field can be substituted by the blocks field in most cases. https://getkirby.com/docs/reference/panel/fields/blocks

If you are running Kirby < 3.5 and cannot upgrade, can try to use version 1.x of this plugin instead (legacy branch), but please be aware, that I cannot provide any support for that version any more.
