### ISSUE TITLE
[1.0.9] Multiple MarkdownBlocks [2rc1] works but Modals do open n-times

### ISSUE THREAD

**Issue by teichsta** [fabianmichael/kirby-markdown-field#134]
Hi,

first, thanks for your awesome work!

Due to some customisation i am stuck to kirby 3.5 for some time. Thus i use v1.0.9 rather than 2rc1 as it requires 3.6. Nevertheless i'd like to use the field as block editor whiich in general works fine (just copied your MarkdownBlock in my button customisation project).

However when it comes to modals it seems that in the block preview the Link and Email modals does not open at all. The Page and File modals do open n-times (amount of markdown editor blocks). Using the same buttons in the drawer of the block (click on pencil) everything works as expected.

I thought about setting ids fpr the block but i didn't figured out the culprit of these multiple modals. Could you direct me into the right direction? Any help is appreciated. Thanks :)

**Comment by teichsta** [comment]
i`ve added `:id="_uid"` field which seems to prevent opening the other dialogs:

```<template>
  <div @dblclick.stop>
    <k-markdown-input
      ref="input"
      :id="_uid"
      :blank="blank"
      :buttons="buttons"
      :custom-highlights="customHighlights"
      :disabled="disabled"
      :font="font"
      :highlights="highlights"
      :kirbytext="kirbytext"
      :known-kirbytags="knownKirbytags"
      :placeholder="placeholder"
      :size="size"
      :value="content.text"
      :endpoints="endpoints"
      :spellcheck="spellcheck"
      :uploads="uploads"
      class="k-block-type-markdowndr-input"
      @input="update({ text: $event })"
    />
  </div>
</template>```

**Comment by teichsta** [comment]
would be great if you could add these changes to the next rc (if you like)

**Comment by fabianmichael** [comment]
> > but still, the other modals (link, file, email) do not open properly.
> 
> ok, got it … the modals property should be added, too which causes the modals to open as configured :)

@teichsta I’m afraid that I don’t understand? Why did you close the ticket, if this issue still exists? Using the field within a blocks/layout field should work without any additional confuguration.

**Comment by teichsta** [comment]
@fabianmichael i closed the ticket, because i didn't want to bother you, sorry. I am glad that you find my findings interesting. If i'd the time i am going to provide a PR containing the above mentioned findings. Thanks again for your great work.
