### ISSUE TITLE
[1.0.9] Textarea does not use the disabled color when field is disabled

### ISSUE THREAD

**Issue by teichsta** [fabianmichael/kirby-markdown-field#135]
In my usecase the editor is disabled due to certain permissions.

When setting the markdown field to disabled it is no longer editable (as expected). Unfortunately it doesn't completely take the disabled color (at least in my case):

![image](https://user-images.githubusercontent.com/2108636/155191566-775fc9ed-e11e-42d9-a20f-f9facd615580.png)

Is there any option which i could tweak to solve this?

Thanks in advance, Thomas E.-E.

**Comment by fabianmichael** [comment]
@teichsta As I don’t support version 1 anymore and haven’t worked on it, I cannot really tell. But if any attribute set, you can probably easly overrise things with a custom `panel.css`, see: https://getkirby.com/docs/cookbook/panel/customizing-panel
