### ISSUE TITLE
Disabled is not disabled

### ISSUE THREAD

**Issue by medienbaecker** [fabianmichael/kirby-markdown-field#137]
While the field gets the correct styling you can still edit text. Interestingly enough it does not save the content though.

![disabled](https://user-images.githubusercontent.com/7975568/161023592-cb29f7c1-9c98-4baa-ad72-63069ab64440.gif)

**Comment by fabianmichael** [comment]
@medienbaecker I tried to solve this, but I could not figure out how to prevent focus on the editor in disabled state … maybe you got an idea? I won’t spend any more time on this for now, though I agree that this feature should work.

**Comment by medienbaecker** [comment]
I don't think it's too bad as it doesn't save the content.
Do you think the stable release of CodeMirror 6 will help with stuff like this? I'll try to dig into the code once I have a few free minutes.

**Comment by fabianmichael** [comment]
@medienbaecker I tried with the stable release and updated all dependencies this morning, did the necessary refactoring etc. but still no luck. But I’m probably missing out something, maybe it has something to do with "Facets", some concept used for defining extensions for CM.
