### ISSUE TITLE
Trying to add link results in error

### ISSUE THREAD

**Issue by heyfordy** [fabianmichael/kirby-markdown-field#139]
Hey, not sure what the deal is but when I try to add a link from the format bar, the editor disappears and is replaced by a red error toast reading:

```Cannot read properties of undefined (reading 'info').```

Any ideas what could be causing this?

**Comment by fabianmichael** [comment]
@heyfordy Can you please provide me the following information?

- Kirby version
- plugin version
- Blueprint, where the field is defined

That would help a lot with tracking down the error, thanks.

**Comment by heyfordy** [comment]
Okay, looks like for some reason composer was installing version `0.1.0` (as defined by the package.json) -- I grabbed a later release from github and threw it in my plugins directory and it works fine now. I didn't even see version 0.1.0 on packagist, so I'm not sure why this version was being provided.

**Comment by fabianmichael** [comment]
@heyfordy Thanks for the update, will close this ticket now.
