### ISSUE TITLE
Composer update

### ISSUE THREAD

**Issue by janstieler** [fabianmichael/kirby-markdown-field#142]
Could you please update your composer package?

Thanks and cheers

**Comment by janstieler** [comment]
Okay, actually I just saw that it is RC.

**Comment by fabianmichael** [comment]
> Okay sorry, actually I just saw that it is RC.

Sorry, I’m afraid I can’t follow you …

**Comment by fabianmichael** [comment]
Closing this, since the was no further reaction …

**Comment by janstieler** [comment]
Sorry for no reaction. I havn't recognized your answer.
If i update the plugin with composer the last version would not load.
But I think you haven't updated the composer package because its actually RC and not the final release.

Cheers.

**Comment by fabianmichael** [comment]
The good thing is: CodeMirror 6.0 now has a stable release. If nothing else breaks, we are close to a stable release for this plugin, too. :-)
