### ISSUE TITLE
Currently not working with Kirby 3.7

### ISSUE THREAD

**Issue by Werbschaft** [fabianmichael/kirby-markdown-field#146]
The markdown field shows an error when using with 3.7

<img width="575" alt="Bildschirmfoto 2022-06-22 um 10 37 18" src="https://user-images.githubusercontent.com/2178466/174984079-ade4cf36-08dd-4893-956a-c8cd9473860b.png">

<img width="596" alt="Bildschirmfoto 2022-06-22 um 10 39 27" src="https://user-images.githubusercontent.com/2178466/174984308-6cf7ba65-88b9-4c9f-9c2b-b89b14b1111f.png">

**Comment by fabianmichael** [comment]
@Werbschaft Thanks for pointing that out. @medienbaecker is currently working on a new PR for with style tweaks, where this has already been fixed. https://github.com/fabianmichael/kirby-markdown-field/pull/145

Please use that branch or remove the check by hand in the meantime. But we can keep this ticket open. This will likely resolved over the next few days.

**Comment by Werbschaft** [comment]
I simply removed the condition and it worked perfectly. It's nice that the plugin still works so well with 3.7.

**Comment by fabianmichael** [comment]
@Werbschaft We merged the style adjustments and the main branch works with 3.7 now.
