### ISSUE TITLE
Codemirror Autocomplete

### ISSUE THREAD

**Issue by pwaldhauer** [fabianmichael/kirby-markdown-field#160]
Hey! I struggled to get autocomplete working in a plugin for your plugin.

I tried to add it in the plugins array (using the indent with tab plugin as a base)

```
 plugins() {
      // An array of CodeMirror plugins provided by this extension
      return [
        autocomplete()
     ];
    }
```

But it just returns errors, something about "Unrecognized extension value in extension set".

I also saw in the source code, that you already added autocomplete, but commented it out?

Is there a possibility to get this working (and to get this working with a custom auto completion source)?

**Comment by fabianmichael** [comment]
@pwaldhauer Please have a look at the changelog of CodeMirror and the autocomplete package. There have been quite a few breaking changes over the last years and maybe try to read my code. I had plans for autocomplete in KirbyTags, but I never found the time for moving these forward.

Besides from that, I cannot really provide any support at this time. However, if you come up with a solution, I’d be happy if you would share it with me.
