### ISSUE TITLE
Remove strict version check

### ISSUE THREAD

**Issue by afbora** [fabianmichael/kirby-markdown-field#162]

**Comment by fabianmichael** [comment]
Yes there are, just did not have the time for testing compatibility so far.

**Comment by medienbaecker** [comment]
I'm using the plugin on 3.9.0 (after manually removing the version check) and didn't notice any issues.

What's the reason for the strict version check, not only for older but also for newer versions? This way the plugin breaks on every major update — no matter if there are breaking changes or not.

**Comment by fabianmichael** [comment]
I don’t remeber the exact reason, but I guess there where some issues in the past. Will remove it …

**Comment by fabianmichael** [comment]
Removed in [4394eba](https://github.com/fabianmichael/kirby-markdown-field/commit/4394eba431d8c091d525e7b683c0660b8a5811b6)

**Comment by MathiasGmeiner** [comment]
Despite the transfer to the main branch, the version has not changed and the latest version is still 2.1.1
Is it possible to create a new release?

**Comment by fabianmichael** [comment]
@MathiasGmeiner Done! :-)

**Comment by MathiasGmeiner** [comment]
@fabianmichael sorry to bother you again, but it looks like packagist has not been updated yet. Is this a manual action or should it happen automatically?

**Comment by fabianmichael** [comment]
@MathiasGmeiner Arg, forgot to update the version in composer.json, so Packagist did not accept the update. Made a new release 2.1.3, should work now.
