### ISSUE TITLE
Question/Feature Request: Link via button as markdown-style rather than kirbytag

### ISSUE THREAD

**Issue by animaux** [fabianmichael/kirby-markdown-field#169]
Thanks for this lovely plugin!

When using the `link`-button, currently a kirby-tag is inserted:

```
(link: https://test.de text: Test)
```

I’d wish a markdown-style link would be included instead:

``` md
[Test](https://test.de)
```

Ideal would maybe be an option to choose from these two, what do you think?

**Comment by fabianmichael** [comment]
This is currently only possible, if KirbyText is disabled in Kirby’s global settings.

**Comment by animaux** [comment]
Thanks Fabian, this sounds like good option for a workaround for me at the moment, since I’m not using kirbytext elsewhere. However I still feel like it would be nice to have this as an option for this extension only.

**Comment by fabianmichael** [comment]
@animaux I've added this feature in the latest `2.1.6` version. :-)

**Comment by animaux** [comment]
Brilliant, thanks! `:D`
