### ISSUE TITLE
Scroll on input

### ISSUE THREAD

**Issue by medienbaecker** [fabianmichael/kirby-markdown-field#179]
On latest Chrome (121.0.6167.160) using 3.0.0-alpha.2 with Kirby 4.1 I experience the following bug:

![CleanShot 2024-02-08 at 17 47 48](https://github.com/fabianmichael/kirby-markdown-field/assets/7975568/3e17f444-0f24-484b-aa7f-0eea87371d08)

As you can see, every time I input any character, the window scrolls. I added transparency to the header background for debugging purposes.

**Comment by tobimori** [comment]
This also happens when using the markdown block in a blocks field

**Comment by medienbaecker** [comment]
I believe this could have something to do with [this issue](https://github.com/getkirby/kirby/issues/5251) and [this pull request](https://github.com/getkirby/kirby/pull/5907). It seems like there was a change in the core textarea regarding the auto height.

**Comment by miragecraft** [comment]
Noticed it too, it's been making my site updates very painful.

**Comment by medienbaecker** [comment]
After spending a few hours debugging and searching for a solution I just updated Chrome to `121.0.6167.184`  (released yesterday) and the issue is fixed 🫠

**Comment by teichsta** [comment]
just fyi: this issues also occurs in v2.2 and is fixed after update to latest Chrome-Version.
