### ISSUE TITLE
Using Codemirror Themes for Syntax Highlighting

### ISSUE THREAD

**Issue by luismqueral** [fabianmichael/kirby-markdown-field#191]
Hi there, thanks so much for contributing this plugin to the Kirby community.

I see in the docs there's support for custom highlighting, but am a little lost on extending things from scratch with regex.

Is there a way to adopt an existing Codemirror theme and edit from there?

**Comment by fabianmichael** [comment]
Hi,

this plugin is solely intended for editing Markdown and the additional highlights are intended for simple things like custom tags, e.g. [`(columns...)`](https://getkirby.com/docs/cookbook/extensions/columns-in-kirbytext) If you need a code editor, you should probably create a fork of the plugin.
