### ISSUE TITLE
On by default

### ISSUE THREAD

**Issue by luxuryluke** [fabianmichael/kirby-markdown-field#78]
I'd love it if after adding the `config` bit to my config, that I wouldn't have to add `type: markdown` on every blueprint where I have a `textarea`.
Is this possible, or am I missing something?

**Comment by sylvainjule** [comment]
I'm really not sure this is easily feasible in K3. Will ask. 

In the meantime, if you do not want to waste time changing everything manually:

```
perl -pi -w -e 's/type: textarea/type: markdown/g;' **/*.yml
```

**Comment by bnomei** [comment]
@sylvainjule maybe one should exclude the `.git` folder or it might end up corrupting the git index.

**Comment by fabianmichael** [comment]
Closing this, as it seemingly affects version 1.0. Version 2 will be released soon, so I won’t go into that any further. Thanks for your understanding.
