### ISSUE TITLE
Bold formatting expanding with space

### ISSUE THREAD

**Issue by medienbaecker** [fabianmichael/kirby-markdown-field#84]
When adding a space to bold text, the bold formatting will expand to the following lines:

![space bold](https://user-images.githubusercontent.com/7975568/67398172-8e2bee80-f5aa-11e9-83bb-9922af544c6c.gif)

**Comment by fabianmichael** [comment]
Unfortunately, the Markdown parser of CodeMirror has some differences from Parsedown (used by Kirby). I’ll have a look, but cannot promise that I can solve this.

**Comment by fabianmichael** [comment]
@medienbaecker FYI, a new version of the plugin has now reached late alpha/early beta., based on CodeMirror 6. It has a much better Markdown parser, which handles this correctly. If you’re adventurous, you should give it a try: https://github.com/sylvainjule/kirby-markdown-field/tree/next

**Comment by fabianmichael** [comment]
Closing this, as it seemingly affects version 1.0. Version 2 will be released soon, so I won’t go into that any further. Thanks for your understanding.
